/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bacaericproject;

/**
 *
 * @author Eric Baca
 */
public class Cart extends javax.swing.JFrame {

    private Items myItems;
    
    /**
     * Creates new form Cart
     */
    public Cart() {
        initComponents();
    }
    
    Cart(Items myItems) {
        initComponents();
        this.myItems = myItems;
        
        ItemEntry item = myItems.getItem("Catalytic Converter"); //getting the item
        double quantity = item.getItemQuantity();
        if(quantity > 0.0) { //If there is a quantity of this item in the cart
            Item1Label.setText("Catalytic Converter"); //display the name of the item
            item1PriceLabel.setText("$" + item.getItemPrice() + "  Quantity"); //display the item price
        }
        else {
            //if item is not in the cart this section will not be visible
            quantityBox1.setVisible(false);
            Item1Label.setVisible(false);
            item1PriceLabel.setVisible(false);
        }
        
        //the prevois steps are repeated for item 1 - item 7
        ItemEntry item2 = myItems.getItem("Fuel Pump");
        quantity = item2.getItemQuantity();
        if(quantity > 0.0) {
            Item2Label.setText("Fuel Pump");
            item2PriceLabel.setText("$" + item2.getItemPrice() + "  Quantity");
        }
        else {
            quantityBox2.setVisible(false);
            Item2Label.setVisible(false);
            item2PriceLabel.setVisible(false);
        }
        
        ItemEntry item3 = myItems.getItem("Carburetor");
        quantity = item3.getItemQuantity();
        if(quantity > 0.0) {
            Item3Label.setText("Carburetor");
            item3PriceLabel.setText("$" + item3.getItemPrice() + "  Quantity");
        }
        else {
            quantityBox3.setVisible(false);
            Item3Label.setVisible(false);
            item3PriceLabel.setVisible(false);
        }
        
        ItemEntry item4 = myItems.getItem("Big Brake Kit");
        quantity = item4.getItemQuantity();
        if(quantity > 0.0) {
            Item4Label.setText("Big Brake Kit");
            item4PriceLabel.setText("$" + item4.getItemPrice() + "  Quantity");
        }
        else {
            quantityBox4.setVisible(false);
            Item4Label.setVisible(false);
            item4PriceLabel.setVisible(false);
        }
        
        ItemEntry item5 = myItems.getItem("Front Bumper");
        quantity = item5.getItemQuantity();
        if(quantity > 0.0) {
            Item5Label.setText("Front Bumper");
            item5PriceLabel.setText("$" + item5.getItemPrice() + "  Quantity");
        }
        else {
            quantityBox5.setVisible(false);
            Item5Label.setVisible(false);
            item5PriceLabel.setVisible(false);
        }
        
        ItemEntry item6 = myItems.getItem("Eric's Emporium T-Shirt");
        quantity = item6.getItemQuantity();
        if(quantity > 0.0) {
            Item6Label.setText("Eric's Emporium T-Shirt");
            item6PriceLabel.setText("$" + item6.getItemPrice() + "  Quantity");
        }
        else {
            quantityBox6.setVisible(false);
            Item6Label.setVisible(false);
            item6PriceLabel.setVisible(false);
        }
        
        ItemEntry item7 = myItems.getItem("Eric's Emportium Adjustable Cap");
        quantity = item7.getItemQuantity();
        if(quantity > 0.0) {
            Item7Label.setText("Eric's Emportium Adjustable Cap");
            item7PriceLabel.setText("$" + item7.getItemPrice() + "  Quantity");
        }
        else {
            quantityBox7.setVisible(false);
            Item7Label.setVisible(false);
            item7PriceLabel.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Item1Label = new java.awt.Label();
        quantityBox1 = new javax.swing.JComboBox<>();
        item1PriceLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Item2Label = new java.awt.Label();
        Item3Label = new java.awt.Label();
        Item5Label = new java.awt.Label();
        Item6Label = new java.awt.Label();
        Item4Label = new java.awt.Label();
        Item7Label = new java.awt.Label();
        item2PriceLabel = new javax.swing.JLabel();
        item3PriceLabel = new javax.swing.JLabel();
        item4PriceLabel = new javax.swing.JLabel();
        item5PriceLabel = new javax.swing.JLabel();
        item6PriceLabel = new javax.swing.JLabel();
        item7PriceLabel = new javax.swing.JLabel();
        quantityBox2 = new javax.swing.JComboBox<>();
        quantityBox3 = new javax.swing.JComboBox<>();
        quantityBox4 = new javax.swing.JComboBox<>();
        quantityBox5 = new javax.swing.JComboBox<>();
        quantityBox6 = new javax.swing.JComboBox<>();
        quantityBox7 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Shopping Cart");

        Item1Label.setText("Item 1");

        quantityBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        quantityBox1.setSelectedIndex(1);
        quantityBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityBox1ActionPerformed(evt);
            }
        });

        item1PriceLabel.setText("$ Price");

        jButton1.setText("Shipping");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Item2Label.setText("Item 2");

        Item3Label.setText("Item 3");

        Item5Label.setText("Item 5");

        Item6Label.setText("Item 6");

        Item4Label.setText("Item 4");

        Item7Label.setText("Item 7");

        item2PriceLabel.setText("$ Price");

        item3PriceLabel.setText("$ Price");

        item4PriceLabel.setText("$ Price");

        item5PriceLabel.setText("$ Price");

        item6PriceLabel.setText("$ Price");

        item7PriceLabel.setText("$ Price");

        quantityBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        quantityBox2.setSelectedIndex(1);
        quantityBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityBox2ActionPerformed(evt);
            }
        });

        quantityBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        quantityBox3.setSelectedIndex(1);
        quantityBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityBox3ActionPerformed(evt);
            }
        });

        quantityBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        quantityBox4.setSelectedIndex(1);
        quantityBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityBox4ActionPerformed(evt);
            }
        });

        quantityBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        quantityBox5.setSelectedIndex(1);
        quantityBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityBox5ActionPerformed(evt);
            }
        });

        quantityBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        quantityBox6.setSelectedIndex(1);
        quantityBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityBox6ActionPerformed(evt);
            }
        });

        quantityBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        quantityBox7.setSelectedIndex(1);
        quantityBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityBox7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Item1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Item2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Item3Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Item5Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Item6Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Item7Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Item4Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item2PriceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item3PriceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item4PriceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item5PriceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item6PriceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item7PriceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item1PriceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(84, 84, 84)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Item1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(quantityBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(item1PriceLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Item2Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(item2PriceLabel)
                        .addComponent(quantityBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Item3Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(item3PriceLabel)
                        .addComponent(quantityBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Item4Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(item4PriceLabel)
                        .addComponent(quantityBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Item5Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(item5PriceLabel)
                        .addComponent(quantityBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Item6Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(item6PriceLabel)
                        .addComponent(quantityBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Item7Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(item7PriceLabel)
                        .addComponent(quantityBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quantityBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int subtotal = 0;
        
        ItemEntry item = myItems.getItem("Catalytic Converter"); //get the item
        item.setItemQuantity(quantityBox1.getSelectedIndex()); //get price of item
        subtotal += item.getItemQuantity() * item.getItemPrice(); //add price * quantity to subtotal
        
        //repeat previous steps for items 1-7 to get a subtotal of all items
        ItemEntry item2 = myItems.getItem("Fuel Pump");
        item2.setItemQuantity(quantityBox2.getSelectedIndex());
        subtotal += item2.getItemQuantity() * item2.getItemPrice();
        
        ItemEntry item3 = myItems.getItem("Catalytic Converter");
        item3.setItemQuantity(quantityBox3.getSelectedIndex());
        subtotal += item3.getItemQuantity() * item3.getItemPrice();
        
        myItems.setSubtotal(subtotal); //set the subtotal
        //starting the next frame
        Shipping myShipping = new Shipping(myItems);
        myShipping.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void quantityBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityBox2ActionPerformed

    private void quantityBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityBox3ActionPerformed

    private void quantityBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityBox4ActionPerformed

    private void quantityBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityBox5ActionPerformed

    private void quantityBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityBox6ActionPerformed

    private void quantityBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityBox7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Item1Label;
    private java.awt.Label Item2Label;
    private java.awt.Label Item3Label;
    private java.awt.Label Item4Label;
    private java.awt.Label Item5Label;
    private java.awt.Label Item6Label;
    private java.awt.Label Item7Label;
    private javax.swing.JLabel item1PriceLabel;
    private javax.swing.JLabel item2PriceLabel;
    private javax.swing.JLabel item3PriceLabel;
    private javax.swing.JLabel item4PriceLabel;
    private javax.swing.JLabel item5PriceLabel;
    private javax.swing.JLabel item6PriceLabel;
    private javax.swing.JLabel item7PriceLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> quantityBox1;
    private javax.swing.JComboBox<String> quantityBox2;
    private javax.swing.JComboBox<String> quantityBox3;
    private javax.swing.JComboBox<String> quantityBox4;
    private javax.swing.JComboBox<String> quantityBox5;
    private javax.swing.JComboBox<String> quantityBox6;
    private javax.swing.JComboBox<String> quantityBox7;
    // End of variables declaration//GEN-END:variables
}
