/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bacaericproject;

/**
 *
 * @author Eric Baca
 */
public class Selection extends javax.swing.JFrame {

        private Items myItems;
        private boolean selectionMade = false;

    
    
    /**
     * Creates new form Selection
     */
    public Selection() {
        initComponents();
    }
    
    Selection(Items myItems) {
        this.myItems = myItems;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        item1Label = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        item1PriceLabel = new javax.swing.JLabel();
        cartCheckBox2 = new java.awt.Checkbox();
        cartButton1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        cartCheckBox1 = new java.awt.Checkbox();
        cartCheckBox3 = new java.awt.Checkbox();
        cartCheckBox4 = new java.awt.Checkbox();
        cartCheckBox5 = new java.awt.Checkbox();
        cartCheckBox6 = new java.awt.Checkbox();
        cartCheckBox7 = new java.awt.Checkbox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        item1Label.setName("item 1"); // NOI18N
        item1Label.setText("Fuel Pump");

        label2.setText("Catalytic Converter");

        label3.setText("Carburetor");

        item1PriceLabel.setText("325.50");

        cartCheckBox2.setLabel(" Add to cart");
        cartCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartCheckBox2MouseClicked(evt);
            }
        });

        cartButton1.setText("Shopping Cart");
        cartButton1.setEnabled(false);
        cartButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartButton1ActionPerformed(evt);
            }
        });

        label1.setText("Big Brake Kit");

        label4.setText("Front Bumper");

        label5.setText("Eric's Emporium T-Shirt");

        label6.setText("Eric's Emporium Adjustable Cap");

        jLabel2.setText("250.25");

        jLabel3.setText("460.00");

        jLabel4.setText("1275.00");

        jLabel5.setText("275.00");

        jLabel6.setText("34.50");

        jLabel7.setText("20.00");

        jPanel1.setBackground(new java.awt.Color(0, 240, 240));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Use code EMPORIUM20 for 20% off your entire order!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel1.setBackground(new java.awt.Color(0, 240, 240));

        jLabel1.setBackground(new java.awt.Color(0, 240, 240));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eric's Car Part Emporium");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cartCheckBox1.setLabel(" Add to cart");
        cartCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartCheckBox1MouseClicked(evt);
            }
        });
        cartCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cartCheckBox1ItemStateChanged(evt);
            }
        });

        cartCheckBox3.setLabel(" Add to cart");
        cartCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartCheckBox3MouseClicked(evt);
            }
        });

        cartCheckBox4.setLabel(" Add to cart");
        cartCheckBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartCheckBox4MouseClicked(evt);
            }
        });

        cartCheckBox5.setLabel(" Add to cart");
        cartCheckBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartCheckBox5MouseClicked(evt);
            }
        });

        cartCheckBox6.setLabel(" Add to cart");
        cartCheckBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartCheckBox6MouseClicked(evt);
            }
        });

        cartCheckBox7.setLabel(" Add to cart");
        cartCheckBox7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartCheckBox7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(item1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(item1PriceLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cartCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cartCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cartCheckBox3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cartCheckBox4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cartCheckBox5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cartCheckBox6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cartCheckBox7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15)
                        .addComponent(cartButton1))
                    .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item1Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item1PriceLabel)
                    .addComponent(cartCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cartCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cartCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cartCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cartCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cartCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cartCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cartButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        item1Label.getAccessibleContext().setAccessibleName("Item 1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cartCheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartCheckBox2MouseClicked
        // TODO add your handling code here:
        boolean toggled = cartCheckBox2.getState();
        if (toggled == false){
            cartButton1.setEnabled(true); //This validation system will be changed
        }
        else {
            cartButton1.setEnabled(false);
        }
        
    }//GEN-LAST:event_cartCheckBox2MouseClicked

    private void cartButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartButton1ActionPerformed
        // TODO add your handling code here:
        boolean added = cartCheckBox2.getState();
        if(added == true) {
            //checks if the item is selected, if true, gets the item 
            //and modifys it accordingly
            ItemEntry item = myItems.getItem("Catalytic Converter");
            item.setAddToCart(true);
            item.setItemQuantity(1);
        }
        
        added = cartCheckBox1.getState();
        if (added == true) {
            //checks if the item is selected, if true, gets the item 
            //and modifys it accordingly
            ItemEntry item = myItems.getItem("Fuel Pump");
            item.setAddToCart(true);
            item.setItemQuantity(1);
        }
        
        added = cartCheckBox3.getState();
        if (added == true) {
            //checks if the item is selected, if true, gets the item 
            //and modifys it accordingly
            ItemEntry item = myItems.getItem("Carburetor");
            item.setAddToCart(true);
            item.setItemQuantity(1);
        }
        
        added = cartCheckBox4.getState();
        if (added == true) {
            //checks if the item is selected, if true, gets the item 
            //and modifys it accordingly
            ItemEntry item = myItems.getItem("Big Brake Kit");
            item.setAddToCart(true);
            item.setItemQuantity(1);
        }
        
        added = cartCheckBox5.getState();
        if (added == true) {
            //checks if the item is selected, if true, gets the item 
            //and modifys it accordingly
            ItemEntry item = myItems.getItem("Front Bumper");
            item.setAddToCart(true);
            item.setItemQuantity(1);
        }
        
        added = cartCheckBox6.getState();
        if (added == true) {
            //checks if the item is selected, if true, gets the item 
            //and modifys it accordingly
            ItemEntry item = myItems.getItem("Eric's Emporium T-Shirt");
            item.setAddToCart(true);
            item.setItemQuantity(1);
        }
        
        added = cartCheckBox7.getState();
        if (added == true) {
            //checks if the item is selected, if true, gets the item 
            //and modifys it accordingly
            ItemEntry item = myItems.getItem("Eric's Emportium Adjustable Cap");
            item.setAddToCart(true);
            item.setItemQuantity(1);
        }
        //starting the next jframe
        Cart myCart = new Cart(myItems);
        myCart.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cartButton1ActionPerformed

    private void cartCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartCheckBox1MouseClicked
        // TODO add your handling code here:
        boolean toggled = cartCheckBox1.getState();
        if (toggled == false){
            cartButton1.setEnabled(true); //temporary
        }
        else {
            cartButton1.setEnabled(false);
        }
    }//GEN-LAST:event_cartCheckBox1MouseClicked

    private void cartCheckBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartCheckBox3MouseClicked
        // TODO add your handling code here:
        boolean toggled = cartCheckBox3.getState();
        if (toggled == false){
            cartButton1.setEnabled(true);
        }
        else {
            cartButton1.setEnabled(false);
        }
    }//GEN-LAST:event_cartCheckBox3MouseClicked

    private void cartCheckBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartCheckBox4MouseClicked
        // TODO add your handling code here:
        boolean toggled = cartCheckBox4.getState();
        if (toggled == false){
            cartButton1.setEnabled(true);
        }
        else {
            cartButton1.setEnabled(false);
        }
    }//GEN-LAST:event_cartCheckBox4MouseClicked

    private void cartCheckBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartCheckBox5MouseClicked
        // TODO add your handling code here:
        boolean toggled = cartCheckBox5.getState();
        if (toggled == false){
            cartButton1.setEnabled(true);
        }
        else {
            cartButton1.setEnabled(false);
        }
    }//GEN-LAST:event_cartCheckBox5MouseClicked

    private void cartCheckBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartCheckBox6MouseClicked
        // TODO add your handling code here:
        boolean toggled = cartCheckBox6.getState();
        if (toggled == false){
            cartButton1.setEnabled(true);
        }
        else {
            cartButton1.setEnabled(false);
        }
    }//GEN-LAST:event_cartCheckBox6MouseClicked

    private void cartCheckBox7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartCheckBox7MouseClicked
        // TODO add your handling code here:
        boolean toggled = cartCheckBox7.getState();
        if (toggled == false){
            cartButton1.setEnabled(true);
        }
        else {
            cartButton1.setEnabled(false);
        }
    }//GEN-LAST:event_cartCheckBox7MouseClicked

    private void cartCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cartCheckBox1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cartCheckBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selection().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cartButton1;
    private java.awt.Checkbox cartCheckBox1;
    private java.awt.Checkbox cartCheckBox2;
    private java.awt.Checkbox cartCheckBox3;
    private java.awt.Checkbox cartCheckBox4;
    private java.awt.Checkbox cartCheckBox5;
    private java.awt.Checkbox cartCheckBox6;
    private java.awt.Checkbox cartCheckBox7;
    private java.awt.Label item1Label;
    private javax.swing.JLabel item1PriceLabel;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
