/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bacaericproject;



/**
 *
 * @author Eric Baca
 */
public class Shipping extends javax.swing.JFrame {

    private double baseP = 15.0;
    private double shippingMultip;
    private int selection;
    private double shippingCost;
    private boolean sameDayShip = false;
    private boolean enteredState = false;
    private Items myItems;
    
    
    
    /**
     * Creates new form Shipping
     */
    public Shipping() {
        initComponents();
    }
    
    Shipping(Items myItems) {
        
        this.myItems = myItems;
        initComponents();
    }
        /*
    private double calcShipping(double baseP, int shippingMultip, boolean sameDayShip) {
        //calculate shipping
        return 0.0;
    }
        */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        locationComboBox = new javax.swing.JComboBox<>();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        isSameDayShipping = new java.awt.Checkbox();
        jButton1 = new javax.swing.JButton();
        checkoutButton1 = new javax.swing.JButton();
        shippingCostLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label1.setText("Shipping Price Calculator");

        locationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ME", "VT", "NH", "MA", "CT", "RI", "NY", "PA", "NJ", "DE", "MD", "OH", "WV", "VA", "MI", "WI", "IL", "IN", "KY", "NC", "TN", "SC", "GA", "AL", "FL", "LA", "AR", "MO", "IA", "MN", "TX", "OK", "KS", "NE", "SD", "ND", "MT", "WY", "CO", "NM", "AZ", "UT", "ID", "WA", "OR", "NV", "CA", "AK", "HI" }));
        locationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationComboBoxActionPerformed(evt);
            }
        });

        label2.setText("State:");

        label3.setText("Same day shpping: ");

        isSameDayShipping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                isSameDayShippingMouseClicked(evt);
            }
        });

        jButton1.setText("Calculate shipping cost");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        checkoutButton1.setText("Checkout");
        checkoutButton1.setEnabled(false);
        checkoutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isSameDayShipping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(shippingCostLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButton1)
                .addGap(0, 128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(checkoutButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isSameDayShipping, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(14, 14, 14)
                .addComponent(shippingCostLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(checkoutButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void locationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationComboBoxActionPerformed
        // TODO add your handling code here:
        enteredState = true;
        
        selection = locationComboBox.getSelectedIndex();
        if (selection == 0) {
            while(selection == 0) {
                //display error asking for location
            }
        }
        jButton1.setEnabled(true); //enables the calculate shipping button
        //the following if-else statements are based on distance from 
        //the shipping location, states closer to the east coast are cheaper
        //to ship from, so shipping cost multiplies the further you go west
        if (selection <= 10 && selection > 0) {
            shippingMultip = 1;
            myItems.setShippingDate("2-3 Days");
        }
        else if (selection > 10 && selection <= 20) {
            shippingMultip = 1.5;
            myItems.setShippingDate("4-5 Days");
        }
        else if (selection > 20 && selection <= 30) {
            shippingMultip = 3;
            myItems.setShippingDate("5-6 Days");
        }
        else if (selection > 30 && selection <= 40) {
            shippingMultip = 3.5;
            myItems.setShippingDate("6-7 Days");
        }
        else if (selection > 40 && selection <= 48) {
            shippingMultip = 5;
            myItems.setShippingDate("7-9 Days");
        }
        else if (selection == 49 || selection == 50) {
            shippingMultip = 7;
            myItems.setShippingDate("10-12 Days");
        }
    }//GEN-LAST:event_locationComboBoxActionPerformed

    private void isSameDayShippingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_isSameDayShippingMouseClicked
        // TODO add your handling code here:
        
        boolean toggled = isSameDayShipping.getState(); //gets the state of the checkbox
        if (toggled == false){
            sameDayShip = true;
        }
        else {
            sameDayShip = false;
        }
    }//GEN-LAST:event_isSameDayShippingMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        shippingCost = baseP * shippingMultip;
        
        if(sameDayShip == false) { //calculating shipping based on distance
            shippingCost = baseP * shippingMultip;
        }
        else if(sameDayShip == true) {//calculating shipping based on distance and multiplying for single day shipping upcharge
            shippingCost = (baseP * shippingMultip) * 3;
            myItems.setShippingDate("1 Day");//confirmation page display if shipping is 1 day
        }
        //display shipping cost
        shippingCostLabel1.setText("Estimated shipping: $" + shippingCost);
        checkoutButton1.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkoutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButton1ActionPerformed
        // TODO add your handling code here:
        myItems.setShippingCost(shippingCost); //sets to the last calculated shipping cost
        //starting the next jframe
        Checkout myCheckout = new Checkout(myItems);
        myCheckout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checkoutButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shipping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shipping().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkoutButton1;
    private java.awt.Checkbox isSameDayShipping;
    private javax.swing.JButton jButton1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JComboBox<String> locationComboBox;
    private javax.swing.JLabel shippingCostLabel1;
    // End of variables declaration//GEN-END:variables
}
